workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Fix CocoaPods repo & install
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod setup
          pod repo update
          pod install
          pod update GTMSessionFetcher/Core
          cd ..
      - name: Build iOS debug
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/**/*.dSYM
