workflows:
  default-workflow:
    name: Driver App Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx4096m"
    scripts:
      - name: Clean Flutter
        script: |
          flutter clean
      - name: Get Dependencies
        script: |
          flutter pub get
      - name: iOS CocoaPods Fix
        script: |
          cd ios
          pod repo update
          pod install
          pod update GTMSessionFetcher/Core
          cd ..
      - name: Build Android AppBundle
        script: |
          flutter build appbundle --debug
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/app/outputs/**/*.aab
      - build/ios/iphoneos/*.app
      - build/ios/**/*.dSYM
