workflows:
  ios-debug:
    name: iOS & Android Debug Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        GRADLE_OPTS: -Xmx4096m
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Update CocoaPods & resolve conflicts
        script: |
          cd ios
          pod repo update
          pod install
          pod update GTMSessionFetcher/Core
          cd ..
      - name: Build iOS debug
        script: |
          flutter build ios --debug --no-codesign
      - name: Build Android debug bundle
        script: |
          flutter build appbundle --debug
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/**/*.dSYM
      - build/app/outputs/**/*.aab
