workflows:
  default-workflow:
    name: Driver App Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx4096m"
    scripts:
      - name: Clean Flutter
        script: |
          flutter clean
      - name: Get Dependencies
        script: |
          flutter pub get
      - name: iOS CocoaPods Fix
        script: |
          cd ios
          rm -rf Pods Podfile.lock ~/Library/Caches/CocoaPods ~/.cocoapods
          pod repo remove master || true
          pod setup
          pod install --repo-update
          pod update GTMSessionFetcher/Core
          cd ..
      - name: Increase Gradle heap size
        script: |
          sed -i '' '/org.gradle.jvmargs/d' android/gradle.properties
          echo "org.gradle.jvmargs=-Xmx6g" >> android/gradle.properties


      - name: Build Android AppBundle
        script: |
          flutter build appbundle --debug
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/app/outputs/**/*.aab
      - build/ios/iphoneos/*.app
      - build/ios/**/*.dSYM

  ios-debug:
    name: iOS Debug Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Reset CocoaPods & update GTMSessionFetcher
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          pod update GTMSessionFetcher/Core
          cd ..
      - name: Build iOS debug
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/**/*.dSYM
