workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Clean CocoaPods and update repos
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod setup
          pod install --repo-update
          cd ..
      - name: Build iOS Debug (no codesign)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/**/*.dSYM
